version: "3.8"

services:
  server:
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    container_name: server
    depends_on:
      - redis
      - database
    environment:
      - PGDATABASE=taxi
      - PGUSER=taxi
      - PGPASSWORD=taxi
      - PGHOST=database
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 8003:8000
    volumes:
      - ./server:/usr/src/app

  redis:
    container_name: redis
    image: redis:7-alpine

  database:
    container_name: database
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
    expose:
      - 5432
    volumes:
      - database:/var/lib/postgresql/data

  client:
    build:
      context: ./client
    command: yarn start
    container_name: client
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:8003
      - REACT_APP_GOOGLE_MAPS_KEY=<YOUR_API_KEY>
    ports:
      - 3001:3000
    stdin_open: true
    volumes:
      - ./client:/usr/src/app

volumes:
  database:
